# Generated by Django 2.2.7 on 2020-05-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=30)),
                ('tamanho', models.CharField(max_length=2)),
                ('quantidade', models.IntegerField()),
                ('tipo', models.CharField(choices=[('C', 'Calçados'), ('V', 'Vestuario'), ('A', 'Acessorios')], max_length=1)),
            ],
        ),
    ]
